### ISSUE TITLE
【疑问】hitTest 方法是如何有效的防止 button 被点击多次，来防止导致动画异常的？

### ISSUE THREAD

**Issue by chrayon** [dgytdhy/DGExpandMenuButton#1]
如果在点击 main button 后，main button 仍然可以被点击，会导致动画异常，但是我看到你解决了这个问题。希望能学习下思路

**Comment by Desgard** [comment]
这里的hitTest是来检查背景View被点击的时候，不被响应。如代码所示，我在button后面做了一个与屏幕尺寸相同的view，意在方便的改变背景色。而mainbutton的点击响应在menu展开后不被处理，是因为alpha值小于0.1。在UIView中有一条规则，即当一个视图View的alpha小于0.1，则不处理任何任何的手势。我通过alpha变换来达到的效果。
如果想了解更多，强烈推荐_iOS Core Animation: Advanced Techniques_这本书。

**Comment by chrayon** [comment]
我后来又看了下代码，并做了测试，如你所说，你使用了 HitTest 在 response chain 中阻止了后续的点击。

是不是因为在 UIView 的 animation Block 中，只要设置了 alpha，即使动画没有完全执行完毕，它的属性的确已经改变了。

**Comment by Desgard** [comment]
是的，你的猜测是对的。其实UIView是Core Animation的简单实现罢了。我凭经验（因为看不到源码），觉得内部实现原理是：layer层上加上了animation，到执行结束后在让View的属性发生改变。
在UIView Animation中，过程是无法捕捉状态的。对此iOS10提供了新的feature，通过Animator Class可以让动画暂停，通过一个类似于NSProgress的比例过程量来暂停、抹除、续接动画。
可参考[此文](http://jamesonquave.com/blog/designing-animations-with-uiviewpropertyanimator-in-ios-10-and-swift-3/)
